### ISSUE TITLE
评论区后端没有验证uid的正确性，导致可以伪造评论

### ISSUE THREAD

**Issue by shuaitq** [Bokjan/2ZOJ#3]
# Bug原因
1. 评论uid参数由前端js提交给后端[problem_discussion.html](https://github.com/Bokjan/2ZOJ/blob/master/Web/Tpl/problem_discussion.html#L11)
2. 后端再接收到uid参数之后并没有验证正确性[ProblemController.class.php](https://github.com/Bokjan/2ZOJ/blob/master/Web/Controller/ProblemController.class.php#L356)导致可以伪造评论
# 修复建议
1. 在后端添加验证代码保证uid的正确性

**Comment by Bokjan** [comment]
Fixed.
